Name,Description,EDS,Spec,Bus,Device,Function,IOType,Path String,Parent Field Name,Register Name, Error Type, Offset, Actual, Expected,Help, Comment
Power Management,Power Management Checklist,NA,NA,-1,-1,-1,,B00 D14 F0 XHCI Controller,50h Reserved,[23:20] Reserved,ERROR,50,0xC,0xD,,
Power Management,Power Management Checklist,NA,NA,-1,-1,-1,,B00 D14 F0 XHCI Controller,50h Reserved,[19:16] Reserved,ERROR,50,0xE,0xF,,
Power Management,Power Management Checklist,NA,NA,-1,-1,-1,,B00 D14 F0 XHCI Controller,50h Reserved,[9:8] Reserved,ERROR,50,0x2,0x1,,
Power Management,Power Management Checklist,NA,NA,-1,-1,-1,,B00 D14 F0 XHCI Controller,50h Reserved,[7:5] Reserved,ERROR,50,0x2,0x1,,
AntiTheft,Anti-Theft Technology,NA,Intel® Anti-Theft Technology 4.0 BWG Rev0.9,-1,-1,-1,,,,SMBios Type 131 Offset 18h[13] Intel® AT supported,ERROR,49205d33,0x0,0x1,,
Haswell SA BIOS Spec,Haswell System Agent BIOS Spec 0.7.1,,,-1,-1,-1,,B00 D00 F0,7.2 High Definition Audio Controller Configuration,54h [5],ERROR,54,0x0,0x1,,"D1F0 Disabled

"
Haswell SA BIOS Spec,Haswell System Agent BIOS Spec 0.7.1,,,-1,-1,-1,memory,B00 D02 F0,7.2 High Definition Audio Controller Configuration,GTTMMADR 45400h [31],ERROR,45400,0x0,0x1,,"D1F0 Disabled

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D14 F0 XHCI Controller,44h XHCC2-xHC System Bus Configuration Register 2,[11] Reserved,ERROR,44,0x0,0x1,"Attribute: R/WO
Default: 0
",See BIOS Spec Section 22.13.2.1 xHCI Controller Setup
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1B F0 Audio Controller,43h HDINIT1 - Intel® High Definition Audio Initialization Register 1,[6] Reserved,ERROR,43,0x0,0x1,,See BIOS Spec Section 9.5 Additional High Definition Audio Programming Steps
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F0 PCI Express Controller,68h DCTL2 - Device Control 2 Register,[14:13] Reserved,ERROR,68,0x0,0x3,"Default: 0
",See BIOS Section Spec 22.8.14.1Power Optimizer Configuration
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F0 PCI Express Controller,E8h PECR1 - PCI Express* Configuration Register 1,[0] Reserved,ERROR,e8,0x0,0x1,"Default: 0
","See BIOS Spec Section 19.10 Enabling Clock Gating

See BIOS Spec Section 19.10 Enabling Clock Gating"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,64h DCAP2 - Device Capabilities 2 Register,[19:18] Reserved,ERROR,64,0x0,0x2,"Default: 0
",See BIOS Section Spec 22.8.14.1Power Optimizer Configuration
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,68h DCTL2 - Device Control 2 Register,[14:13] Reserved,ERROR,68,0x0,0x3,"Default: 0
",See BIOS Section Spec 22.8.14.1Power Optimizer Configuration
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,68h DCTL2 - Device Control 2 Register,[10] Reserved,ERROR,68,0x0,0x1,"Default: 0
",See BIOS Section Spec 22.8.14.1Power Optimizer Configuration
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,E1h RPDCGEN - Root Port Dynamic Clock Gating Enable Register,[5:2]  Reserved,ERROR,e1,0x0,0xF,"Attribute: R/W
Default: 0
","See BIOS Spec Section 19.10 Enabling Clock Gating

See BIOS Spec Section 19.10 Enabling Clock Gating"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,F4h Reserved,[7] Reserved,ERROR,f4,0x0,0x1,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.8.14Additional PCI Express* Programming Steps

Function 0 only"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,F4h Reserved,[6:5] Reserved,ERROR,f4,0x2,0x0,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.8.14Additional PCI Express* Programming Steps

Function 0 only"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,F5h Reserved,[3:0] Reserved,ERROR,f5,0x0,0x5,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

See BIOS Spec Section 22.19.4 Additional Power Management Programming"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F1 PCI Express Controller,F7h Reserved,[3:2] Reserved,ERROR,f7,0x3,0x0,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.8.14 Additional PCI Express* Programming Steps

Function 0, Function 4 and Function 5 only"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F3 PCI Express Controller,64h DCAP2 - Device Capabilities 2 Register,[19:18] Reserved,ERROR,64,0x0,0x2,"Default: 0
",See BIOS Section Spec 22.8.14.1Power Optimizer Configuration
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F3 PCI Express Controller,68h DCTL2 - Device Control 2 Register,[14:13] Reserved,ERROR,68,0x0,0x3,"Default: 0
",See BIOS Section Spec 22.8.14.1Power Optimizer Configuration
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F3 PCI Express Controller,E1h RPDCGEN - Root Port Dynamic Clock Gating Enable Register,[5:2]  Reserved,ERROR,e1,0x0,0xF,"Attribute: R/W
Default: 0
","See BIOS Spec Section 19.10 Enabling Clock Gating

See BIOS Spec Section 19.10 Enabling Clock Gating"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F3 PCI Express Controller,F4h Reserved,[7] Reserved,ERROR,f4,0x0,0x1,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.8.14Additional PCI Express* Programming Steps

Function 0 only"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F3 PCI Express Controller,F4h Reserved,[6:5] Reserved,ERROR,f4,0x2,0x0,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.8.14Additional PCI Express* Programming Steps

Function 0 only"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F3 PCI Express Controller,F5h Reserved,[3:0] Reserved,ERROR,f5,0x0,0x5,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

See BIOS Spec Section 22.19.4 Additional Power Management Programming"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1C F3 PCI Express Controller,F7h Reserved,[3:2] Reserved,ERROR,f7,0x3,0x0,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.8.14 Additional PCI Express* Programming Steps

Function 0, Function 4 and Function 5 only"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1D F0 EHCI #1 Controller\Host Controller Capability Registers,20h CMD - USB 2.0 Command Register,[1] Host Controller Reset (HCRESET),ERROR,20,0x0,0x1,"Attribute: R/W
Default: 0
This control bit used by software to reset the host controller. The effects of this on root hub registers are similar to a Chip Hardware Reset (i.e., RSMRST# assertion and PWROK deassertion on the PCH). When software writes a 1 to this bit, the host controller resets its internal pipelines, timers, counters, state machines, etc. to their initial value. Any transaction currently in progress on USB is immediately terminated. A USB reset is not driven on downstream ports.

NOTE: PCI configuration registers and Host controller capability registers are not effected by this reset.

All operational registers, including port registers and port state machines are set to their initial values. Port ownership reverts to the companion host controller(s), with the side effects described in the EHCI spec. Software must re-initialize the host controller in order to return the host controller to an operational state.

This bit is set to 0 by the host controller when the reset process is complete. Software cannot terminate the reset process early by writing a 0 to this register.

Software should not set this bit to a 1 when the HCHalted bit (D29:F0,:CAPLENGTH + 24h, bit 12) in the USB2.0_STS register is a 0. Attempting to reset an actively running host controller will result in undefined behavior. This reset me be used to leave EHCI port test modes.","D26/D29 24h [12] is 1.  This value should be set to 1

See BIOS Spec 12.9 Additional Programming Requirements during USB Initialization

See BIOS Spec Section 12.10 Additional Programming Requirements During USB Initialization"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1F F0 LPC Controller,A0h GEN_PMCON_1 - General PM Configuration 1 Register,[2] PCI CLKRUN# Enable (CLKRUN_EN),ERROR,a0,0x0,0x1,"Attribute: R/W
Default: 0
0 = Disable. PCH drives the CLKRUN# signal low.
1 = Enable CLKRUN# logic to control the system PCI clock using the CLKRUN# and STP_PCI# signals.

NOTES:
1. When the SLP_EN# bit is set, the PCH drives the CLKRUN# signal low regardless of the state of the CLKRUN_EN bit. This ensures that the PCI and LPC clocks continue running during a transition to a sleep state.
2. This bit should be set mutually exclusive with the PSEUDO_CLKRUN_EN bit. Setting CLKRUN_EN in a non-mobile SKU could result in unspecified behavior.","See BIOS Spec Section 19.10 Enabling Clock Gating

mobile"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,,B00 D1F F0 LPC Controller,DCh BIOS_CNTL - BIOS Control Register,[5] SMM BIOS write protect disable (SMM_BWP),ERROR,dc,0x0,0x1,"Attribute: R/WLO
Default: 1
This bit set defines when the BIOS region can be written by the host.
0 = BIOS region SMM protection is disabled. The BIOS Region is writable regardless if Processors are in SMM or not. (Set this field to 0 for legacy behavior)
1 = BIOS region SMM protection is enabled. The BIOS Region is not writable unless all Processors are in SMM.","See BIOS Spec Section 3.6 Flash Security Recommendation -- This recommendation is only for production BIOS

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,1030h Reserved,[22] Configuration 1,ERROR,1030,0x0,0x1,"Attribute: RW
","See BIOS Spec 8.11 Subtractive Decode

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,2B1Ch Reserved,[31:0] Reserved,ERROR,2b1c,0x23808033,0x3000088,,"See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,2B2Ch Reserved,[31:0] Reserved,ERROR,2b2c,0x0,0x8813,,"See BIOS Spec Section 22.19.13 Power Optimizer Considerations

mobile"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,2B34h Reserved,[31:0] Reserved,ERROR,2b34,0x80000009,0x80000008,,"See BIOS Spec Section 22.19.4 Additional Power Management Programming

mobile"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller,Memory Mapped IO,3314h CIR3314 - Chipset Initialization Register 3314,ERROR,3314,0x12FFF,0x00016FFF,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,333Ch CIR333C Chipset Initialization Register 333C,[23:20] Reserved,ERROR,333c,0xC,0x8,"Attribute: RO
Default: 0
","See BIOS Spec Section 22.19.10 Enabling Clock Gating

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,3348h CIR3348 - Chipset Initialization Register 3348,[31:0] Reserved,ERROR,3348,0x22DDFFF,0x020DDFFF,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,3368h CIR3368 - Chipset Initialization Register 3368,[31:0] CIR14 Field 1,ERROR,3368,0x41400,0x41000,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,3388h CIR3388 - Chipset Initialization Register 3388,[31:0] CIR16 Field 1,ERROR,3388,0x3F8DDBFF,0x00001000,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,33ACh Reserved,[31:0] Reserved,ERROR,33ac,0x7001,0x1,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,33A8h CIR33A8 - Chipset Initialization Register 33A8,[31:0] CIR16 Field 1,ERROR,33a8,0x181900,0x800,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,33B0h CIR33B0 - Chipset Initialization Register 33B0,[31:0] CIR23 Field 1,ERROR,33b0,0x181900,0x1000,"Attribute: R/W
Default: 0
BIOS must program this field to 00001000h.","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,33C0h CIR33C0 - Chipset Initialization Register 33C0,[31:0] CIR19 Field 1,ERROR,33c0,0x60A00,0x11900,"Attribute: R/W
Default: 0
BIOS must program this field to 00093900h.","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,33D4h CIR33D4 - Chipset Initialization Register 33D4,[19:16] CIR22 Field 1 Upper,ERROR,33d4,0xF,0xB,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,33A8h CIR33A8 - Chipset Initialization Register 33A8,[31:0] CIR33A8 Field 1,ERROR,33a8,0x181900,0x800,"Attribute: R/W
Default: 0
","See BIOS Spec Section 22.19.4 Additional Power Management Programming

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,3400h RC - RTC Configuration Register,[4] Upper 128 Byte Lock (UL),ERROR,3400,0x0,0x1,"Attribute: R/WLO
Default: 0
0 = Bytes not locked.
1 = Bytes 38h-3Fh in the upper 128-byte bank of RTC RAM are locked and cannot be accessed. Writes will be dropped and reads will not return any ensured data. Bit reset on system reset.","See BIOS Spec Section 5.13 BIOS Guide on Using RTC RAM

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,memory,B00 D1F F0 LPC Controller\Memory Mapped IO,3400h RC - RTC Configuration Register,[3] Lower 128 Byte Lock (LL),ERROR,3400,0x0,0x1,"Attribute: R/WLO
Default: 0
0 = Bytes not locked.
1 = Bytes 38h-3Fh in the lower 128-byte bank of RTC RAM are locked and cannot be accessed. Writes will be dropped and reads will not return any ensured data. Bit reset on system reset.","See BIOS Spec Section 5.13 BIOS Guide on Using RTC RAM

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90021CCh Reserved,[31:0] Reserved,ERROR,e90021cc,0x4000,0x354000,"Attribute: RW
Default: 0
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-1

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90023CCh Reserved,[31:0] Reserved,ERROR,e90023cc,0x4000,0x354000,"Attribute: RW
Default: 0
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-1

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90025CCh Reserved,[31:0] Reserved,ERROR,e90025cc,0x4000,0x354000,"Attribute: RW
Default: 0
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-1

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90027CCh Reserved,[31:0] Reserved,ERROR,e90027cc,0x4000,0x354000,"Attribute: RW
Default: 0
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-1

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90029CCh Reserved,[31:0] Reserved,ERROR,e90029cc,0x4000,0x354000,"Attribute: RW
Default: 0
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-1

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E9002BCCh Reserved,[31:0] Reserved,ERROR,e9002bcc,0x4000,0x354000,"Attribute: RW
Default: 0
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-1

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90031CCh Reserved,[31:0] Reserved,ERROR,e90031cc,0x4004,0x355401,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90033CCh Reserved,[31:0] Reserved,ERROR,e90033cc,0x4004,0x355401,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90015CCh Reserved,[31:0] Reserved,ERROR,e90015cc,0x4004,0x355401,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E90017CCh Reserved,[31:0] Reserved,ERROR,e90017cc,0x4004,0x355401,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E9003164h Reserved,[31:0] Reserved,ERROR,e9003164,0x4000,0x5000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E9003364h Reserved,[31:0] Reserved,ERROR,e9003364,0x4000,0x5000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E9001564h Reserved,[31:0] Reserved,ERROR,e9001564,0x4000,0x5000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\PCIe and USB3.0 IOBP Indexed Registers,E9001764h Reserved,[31:0] Reserved,ERROR,e9001764,0x4000,0x5000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-5

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002488h Reserved,[31:0] Reserved,ERROR,ea002488,0x9800,0x8000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002688h Reserved,[31:0] Reserved,ERROR,ea002688,0x9800,0x8000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002494h Reserved,[31:0] Reserved,ERROR,ea002494,0x0,0x80000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002694h Reserved,[31:0] Reserved,ERROR,ea002694,0x0,0x80000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002540h Reserved,[31:0] Reserved,ERROR,ea002540,0x140718,0x180918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002740h Reserved,[31:0] Reserved,ERROR,ea002740,0x140718,0x180918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002544h Reserved,[31:0] Reserved,ERROR,ea002544,0x998,0x0918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002744h Reserved,[31:0] Reserved,ERROR,ea002744,0x998,0x0918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002548h Reserved,[31:0] Reserved,ERROR,ea002548,0x998,0x0918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002748h Reserved,[31:0] Reserved,ERROR,ea002748,0x998,0x0918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002550h Reserved,[31:0] Reserved,ERROR,ea002550,0x0,0x02000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002750h Reserved,[31:0] Reserved,ERROR,ea002750,0x0,0x02000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002554h Reserved,[31:0] Reserved,ERROR,ea002554,0x0,0x020000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002754h Reserved,[31:0] Reserved,ERROR,ea002754,0x0,0x020000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA00257Ch Reserved,[31:0] Reserved,ERROR,ea00257c,0x2400,0x03F00,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA00277Ch Reserved,[31:0] Reserved,ERROR,ea00277c,0x2400,0x03F00,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA0025CCh Reserved,[31:0] Reserved,ERROR,ea0025cc,0x4000,0x354000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA0027CCh Reserved,[31:0] Reserved,ERROR,ea0027cc,0x4000,0x354000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-9

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002088h Reserved,[31:0] Reserved,ERROR,ea002088,0x9800,0x8000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002288h Reserved,[31:0] Reserved,ERROR,ea002288,0x9800,0x8000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002094h Reserved,[31:0] Reserved,ERROR,ea002094,0x0,0x80000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002294h Reserved,[31:0] Reserved,ERROR,ea002294,0x0,0x80000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002140h Reserved,[31:0] Reserved,ERROR,ea002140,0x140718,0x00180918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002340h Reserved,[31:0] Reserved,ERROR,ea002340,0x140718,0x00180918,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002150h Reserved,[31:0] Reserved,ERROR,ea002150,0x0,0x2000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002154h Reserved,[31:0] Reserved,ERROR,ea002154,0x0,0x20000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002350h Reserved,[31:0] Reserved,ERROR,ea002350,0x0,0x2000000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA002354h Reserved,[31:0] Reserved,ERROR,ea002354,0x0,0x20000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA00217Ch Reserved,[31:0] Reserved,ERROR,ea00217c,0x2400,0x03F00,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA00237Ch Reserved,[31:0] Reserved,ERROR,ea00237c,0x2400,0x03F00,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA0021CCh Reserved,[31:0] Reserved,ERROR,ea0021cc,0x4000,0x354000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
Lynxpoint LP BIOS Spec,Lynxpoint LP BIOS Spec 0.7,,0.7,-1,-1,-1,index,B00 D1F F0 LPC Controller\SATA IOBP Indexed Registers,EA0023CCh Reserved,[31:0] Reserved,ERROR,ea0023cc,0x4000,0x354000,"Attribute: RW
","See BIOS Spec Section 7.1.5 Additional PCH DMI Programming Steps Table 7-11

"
CPU 0,CPU 0,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,610h PACKAGE_POWER_LIMIT,[16] CRITICAL_POWER_CLAMP_1,ERROR,610,0x1,0x0,"Attribute: R/W-L
Default: 0
When set, allows processor to go below the OS requested P States in order to maintain the power below Power_Limit_1 value specified below.
This bit is writable only when CPUID.(EAX=06h):EAX[4] is set.
BIOS must not set this bit.",
CPU 0,CPU 0,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,633h C_STATE_LATENCY_CONTROL_3,[9:0] Interrupt Response Time Limit,ERROR,633,0xE4,0x70,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 0,CPU 0,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,634h C_STATE_LATENCY_CONTROL_4,[9:0] Interrupt Response Time Limit,ERROR,634,0x145,0x92,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 0,CPU 0,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[12:10] Time Unit,ERROR,635,0x4,0x2,"Attribute: R/W
Default: 0
This field indicates the unit of measurement for the Interrupt Response Time Limit specified in bits [9:0] of this MSR.
000b - 1ns
001b - 32 ns
010b - 1024 ns
011b - 32768 ns
100b - 1048576 ns
101b - 33554432 ns
110b - reserved
111b - reserved","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 0,CPU 0,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[9:0] Interrupt Response Time Limit,ERROR,635,0x3,0x1BF,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 1,CPU 1,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,610h PACKAGE_POWER_LIMIT,[16] CRITICAL_POWER_CLAMP_1,ERROR,610,0x1,0x0,"Attribute: R/W-L
Default: 0
When set, allows processor to go below the OS requested P States in order to maintain the power below Power_Limit_1 value specified below.
This bit is writable only when CPUID.(EAX=06h):EAX[4] is set.
BIOS must not set this bit.",
CPU 1,CPU 1,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,633h C_STATE_LATENCY_CONTROL_3,[9:0] Interrupt Response Time Limit,ERROR,633,0xE4,0x70,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 1,CPU 1,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,634h C_STATE_LATENCY_CONTROL_4,[9:0] Interrupt Response Time Limit,ERROR,634,0x145,0x92,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 1,CPU 1,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[12:10] Time Unit,ERROR,635,0x4,0x2,"Attribute: R/W
Default: 0
This field indicates the unit of measurement for the Interrupt Response Time Limit specified in bits [9:0] of this MSR.
000b - 1ns
001b - 32 ns
010b - 1024 ns
011b - 32768 ns
100b - 1048576 ns
101b - 33554432 ns
110b - reserved
111b - reserved","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 1,CPU 1,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[9:0] Interrupt Response Time Limit,ERROR,635,0x3,0x1BF,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 2,CPU 2,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,610h PACKAGE_POWER_LIMIT,[16] CRITICAL_POWER_CLAMP_1,ERROR,610,0x1,0x0,"Attribute: R/W-L
Default: 0
When set, allows processor to go below the OS requested P States in order to maintain the power below Power_Limit_1 value specified below.
This bit is writable only when CPUID.(EAX=06h):EAX[4] is set.
BIOS must not set this bit.",
CPU 2,CPU 2,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,633h C_STATE_LATENCY_CONTROL_3,[9:0] Interrupt Response Time Limit,ERROR,633,0xE4,0x70,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 2,CPU 2,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,634h C_STATE_LATENCY_CONTROL_4,[9:0] Interrupt Response Time Limit,ERROR,634,0x145,0x92,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 2,CPU 2,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[12:10] Time Unit,ERROR,635,0x4,0x2,"Attribute: R/W
Default: 0
This field indicates the unit of measurement for the Interrupt Response Time Limit specified in bits [9:0] of this MSR.
000b - 1ns
001b - 32 ns
010b - 1024 ns
011b - 32768 ns
100b - 1048576 ns
101b - 33554432 ns
110b - reserved
111b - reserved","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 2,CPU 2,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[9:0] Interrupt Response Time Limit,ERROR,635,0x3,0x1BF,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 3,CPU 3,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,610h PACKAGE_POWER_LIMIT,[16] CRITICAL_POWER_CLAMP_1,ERROR,610,0x1,0x0,"Attribute: R/W-L
Default: 0
When set, allows processor to go below the OS requested P States in order to maintain the power below Power_Limit_1 value specified below.
This bit is writable only when CPUID.(EAX=06h):EAX[4] is set.
BIOS must not set this bit.",
CPU 3,CPU 3,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,633h C_STATE_LATENCY_CONTROL_3,[9:0] Interrupt Response Time Limit,ERROR,633,0xE4,0x70,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 3,CPU 3,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,634h C_STATE_LATENCY_CONTROL_4,[9:0] Interrupt Response Time Limit,ERROR,634,0x145,0x92,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 3,CPU 3,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[12:10] Time Unit,ERROR,635,0x4,0x2,"Attribute: R/W
Default: 0
This field indicates the unit of measurement for the Interrupt Response Time Limit specified in bits [9:0] of this MSR.
000b - 1ns
001b - 32 ns
010b - 1024 ns
011b - 32768 ns
100b - 1048576 ns
101b - 33554432 ns
110b - reserved
111b - reserved","Please refer to BWG section 17.2.5.2 for more information.

"
CPU 3,CPU 3,N/A,Haswell Processor Family BIOS Writer’s Guide (BWG) 0.71,-1,-1,-1,,,635h C_STATE_LATENCY_CONTROL_5,[9:0] Interrupt Response Time Limit,ERROR,635,0x3,0x1BF,"Attribute: R/W
Default: 0
Specifies the interrupt response time limit that should be used to decide if the package should be put into a Package C3 state.","Please refer to BWG section 17.2.5.2 for more information.

"
D2F0 Graphics,Integrated Graphics Device,Haswell Mobile ULT 0.9v2,,0,2,0,,,02h DID - Device Identification,[15:4] DID_MSB,ERROR,2,0xA1,"A0, A2","Attribute: RO
Default: 40
This is the upper part of a 16 bit value assigned to the Graphics device. Reset value is written to 0x0A0 on CRW by pcode fuse distribution. Bits 5 and 4 are updated based on the GFX level by pcode.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,,,52h  PC - Power Management Capabilities Register,[2:0] Version,ERROR,52,0x3,0x2,"Attribute: RO
Default: 2
Hardwired to 010b. Indicates support for version 1.1 of the PCI Power Management Specification.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,8Ch SDLVI - Stream Descriptor Last Valid Index Register - Input Stream 0,[7:0]  Last Valid Index,ERROR,8c,0x0,>0,"Attribute: RW
Default: 0
The value written to this register indicates the index for the
last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it
will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1  that is, there must be at least 2 valid entries in the buffer
descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,ACh SDLVI - Stream Descriptor Last Valid Index Register - Input Stream 1,[7:0]  Last Valid Index,ERROR,ac,0x0,>0,"Attribute: R/W
Default: 0
The value written to this register indicates the index for the last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1. that is, there must be at least 2 valid entries in the buffer descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,CCh SDLVI - Stream Descriptor Last Valid Index Register - Input Stream 2,[7:0]  Last Valid Index,ERROR,cc,0x0,>0,"Attribute: R/W
Default: 0
The value written to this register indicates the index for the last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1. that is, there must be at least 2 valid entries in the buffer descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,ECh SDLVI - Stream Descriptor Last Valid Index Register - Input Stream 3,[7:0]  Last Valid Index,ERROR,ec,0x0,>0,"Attribute: R/W
Default: 0
The value written to this register indicates the index for the last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1. that is, there must be at least 2 valid entries in the buffer descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,10Ch SDLVI - Stream Descriptor Last Valid Index Register - Output Stream 0,[7:0]  Last Valid Index,ERROR,10c,0x0,>0,"Attribute: R/W
Default: 0
The value written to this register indicates the index for the last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1. that is, there must be at least 2 valid entries in the buffer descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,12Ch SDLVI - Stream Descriptor Last Valid Index Register - Output Stream 1,[7:0]  Last Valid Index,ERROR,12c,0x0,>0,"Attribute: R/W
Default: 0
The value written to this register indicates the index for the last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1. that is, there must be at least 2 valid entries in the buffer descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,14Ch SDLVI - Stream Descriptor Last Valid Index Register - Output Stream 2,[7:0]  Last Valid Index,ERROR,14c,0x0,>0,"Attribute: R/W
Default: 0
The value written to this register indicates the index for the last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1. that is, there must be at least 2 valid entries in the buffer descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
D27F0,Intel(R) High Definition Audio Controller,EDS Spec 1.0, 0.7 ,0,27,0,memory,Memory Mapped Configuration Registers,16Ch SDLVI - Stream Descriptor Last Valid Index Register - Output Stream 3,[7:0]  Last Valid Index,ERROR,16c,0x0,>0,"Attribute: R/W
Default: 0
The value written to this register indicates the index for the last valid Buffer Descriptor in BDL. After the controller has processed this descriptor, it will wrap back to the first descriptor in the list and continue processing.
This field must be at least 1. that is, there must be at least 2 valid entries in the buffer descriptor list before DMA operations can begin.
This value should only modified when the RUN bit is 0.",
PCHD31F0,LPC Interface Bridge,EDS Spec 1.0, 0.7 ,0,31,0,memory,Chipset Configuration Registers,3388h CIR3388 - Chipset Initialization Register 3388,[31:0] CIR3388 Field 1,ERROR,3388,0x3F8DDBFF,0x1000,"Attribute: R/W
Default: 0
BIOS must program this field to 00001000h.","See EDS Spec Section 8.1.73

"
PCHD31F0,LPC Interface Bridge,EDS Spec 1.0, 0.7 ,0,31,0,memory,Chipset Configuration Registers,33B0h CIR33B0 - Chipset Initialization Register 33B0,[31:0] CIR33B0 Field 1,ERROR,33b0,0x181900,0x1000,"Attribute: R/W
Default: 0
BIOS must program this field to 00001000h.","See EDS Spec Section 8.1.76

"
